- hosts: localhost
  tasks:
    - name: Configure kubeconfig
      command: aws eks update-kubeconfig --region us-east-2 --name calculator-devops-cluster

    - name: Apply Kubernetes manifests
      command: kubectl apply -f ../k8s/
